Component removal
Jason-Peralta/weathersite pull request #4
Opened 2021-08-23 17:31 UTC by Jason-Peralta

Removed redundant components from previous mr

2021-08-25 21:12 UTC, alachhman requested changes

2021-08-25 21:12 UTC, alachhman commented on src/App.js
>  });
Refactor your code to use an object similar to the following structure:
```
actual {
  max:
  mean:
  min:
},
average {
  max:
  mean:
  min:
},
record {
  max:
  mean:
  min:
}
```

2021-08-26 23:46 UTC, Jason-Peralta commented on src/App.js
>  });
done

2021-08-26 23:53 UTC, alachhman approved these changes
LGTM

2021-08-26 23:55 UTC, merged